import { useState, useRef, useCallback, useEffect } from 'react';
import { Pose, SequenceState, PoseSlot, EasingFunction } from '../types';
import { 
  getPoseAtTime, 
  getPoseAtScrubPosition, 
  createABSequence, 
  addSlot, 
  removeSlot, 
  updateSlot, 
  reorderSlots,
  updateSlotTransition,
  updateSlotLabel,
  createPoseSlot,
  timeToScrubPosition
} from '../utils/sequenceEngine';

export interface SequenceActions {
  setSequence: (sequence: SequenceState) => void;
  play: () => void;
  pause: () => void;
  stop: () => void;
  setScrubPosition: (position: number) => void;
  setLoop: (loop: boolean) => void;
  addSlot: (pose: Pose, index?: number) => void;
  removeSlot: (slotId: string) => void;
  updateSlot: (slotId: string, pose: Pose) => void;
  reorderSlots: (fromIndex: number, toIndex: number) => void;
  updateSlotTransition: (slotId: string, durationToNext: number, easing: EasingFunction) => void;
  updateSlotLabel: (slotId: string, label: string) => void;
  setABMode: (poseA: Pose, poseB: Pose) => void;
  setEasingEnabled: (enabled: boolean) => void;
  setSmoothTransitions: (enabled: boolean) => void;
  setIKAssisted: (enabled: boolean) => void;
}

export const useSequence = (
  initialPose?: Pose,
  options?: { autoInterpolationEnabled?: boolean }
): [SequenceState, Pose, SequenceActions] => {
  const animationFrameId = useRef<number | null>(null);
  const startTimeRef = useRef<number>(0);
  const pausedTimeRef = useRef<number>(0);
  const depsRef = useRef({ isPlaying: false, slots: [] as PoseSlot[], loop: false });
  const autoInterpolationEnabled = options?.autoInterpolationEnabled ?? false;

  const [sequence, setSequence] = useState<SequenceState>(() => {
    if (initialPose) {
      // Create AB mode with the same pose for both A and B initially
      return createABSequence(initialPose, initialPose);
    }
    return {
      slots: [],
      loop: false,
      isPlaying: false,
      scrubPosition: 0,
      currentTimeMs: 0,
      easingEnabled: true,
      smoothTransitions: true,
      ikAssisted: false
    };
  });

  const [currentPose, setCurrentPose] = useState<Pose>(() => {
    // Safe initialization with proper fallback
    if (initialPose) return initialPose;
    
    // Create a default pose to avoid undefined access
    return {
      root: { x: 0, y: 0 },
      bodyRotation: 0,
      torso: 0,
      waist: 0,
      collar: 0,
      head: 0,
      lShoulder: 0,
      lForearm: 0,
      lWrist: 0,
      rShoulder: 0,
      rForearm: 0,
      rWrist: 0,
      lThigh: 0,
      lCalf: 0,
      lAnkle: 0,
      rThigh: 0,
      rCalf: 0,
      rAnkle: 0
    };
  });

  // Auto-interpolation: Automatically add intermediate poses when slots are far apart
  const applyAutoInterpolation = useCallback((sequenceState: SequenceState): SequenceState => {
    if (sequenceState.slots.length < 2) return sequenceState;

    const newSlots = [...sequenceState.slots];
    const threshold = 2000; // 2 seconds threshold for auto-interpolation
    const maxIntermediateSlots = 2; // Maximum intermediate slots to add total
    const maxTotalSlots = 20; // Upper bound to prevent unlimited accumulation
    let addedSlots = 0;
    let didInsert = false;

    // Check if we're already at the upper bound
    if (newSlots.length >= maxTotalSlots) {
      return sequenceState;
    }

    // Cache original length to avoid issues with array modification during iteration
    const originalLength = newSlots.length;
    
    // Process from end to beginning to avoid index issues when splicing
    for (let i = originalLength - 2; i >= 0 && addedSlots < maxIntermediateSlots && newSlots.length < maxTotalSlots; i--) {
      // Validate indices before accessing array elements
      if (i < 0 || i + 1 >= newSlots.length) {
        continue;
      }
      
      const currentSlot = newSlots[i];
      const nextSlot = newSlots[i + 1];

      if (currentSlot.autoGenerated || nextSlot.autoGenerated) {
        continue;
      }
      
      // Validate slots exist and have valid duration
      if (!currentSlot || !nextSlot || currentSlot.durationToNext <= threshold) {
        continue;
      }

      try {
        // Add intermediate slot
        const intermediateTime = currentSlot.durationToNext / 2;
        const t = 0.5; // Mid-point interpolation
        
        // Use the enhanced interpolation with all features enabled
        const intermediatePose = getPoseAtTime({
          ...sequenceState,
          easingEnabled: true,
          smoothTransitions: true,
          ikAssisted: true
        }, currentSlot.durationToNext * t);
        
        const intermediateSlot = createPoseSlot(intermediatePose, intermediateTime, 'ease-in-out');
        intermediateSlot.label = `${currentSlot.label || String.fromCharCode(65 + i)}→${nextSlot.label || String.fromCharCode(65 + i + 1)}`;
        intermediateSlot.autoGenerated = true;
        
        // Insert at position i + 1
        newSlots.splice(i + 1, 0, intermediateSlot);
        didInsert = true;
        
        // Adjust the current slot's duration
        newSlots[i] = { ...currentSlot, durationToNext: intermediateTime };
        
        addedSlots++;
      } catch (error) {
        console.warn('Failed to create intermediate slot:', error);
        // Continue processing other slots even if one fails
        continue;
      }
    }
    
    return didInsert ? { ...sequenceState, slots: newSlots } : sequenceState;
  }, []);

  // Update current pose when sequence changes
  useEffect(() => {
    if (sequence.slots.length > 0) {
      try {
        const pose = sequence.isPlaying 
          ? getPoseAtTime(sequence, sequence.currentTimeMs)
          : getPoseAtScrubPosition(sequence, sequence.scrubPosition);
        
        if (pose) {
          setCurrentPose(pose);
        }
      } catch (error) {
        console.warn('Error calculating pose from sequence:', error);
        // Fallback to first slot pose or initial pose
        setCurrentPose(sequence.slots[0]?.pose || initialPose || {});
      }
    }
  }, [sequence, initialPose]);

  useEffect(() => {
    if (!autoInterpolationEnabled) return;
    setSequence(prev => applyAutoInterpolation(prev));
  }, [applyAutoInterpolation, autoInterpolationEnabled]);

  const play = useCallback(() => {
    if (sequence.slots.length < 2) return;
    
    setSequence(prev => ({ ...prev, isPlaying: true }));
    startTimeRef.current = performance.now() - pausedTimeRef.current;
  }, [sequence.slots.length]);

  const pause = useCallback(() => {
    setSequence(prev => ({ ...prev, isPlaying: false }));
    pausedTimeRef.current = sequence.currentTimeMs;
    if (animationFrameId.current) {
      cancelAnimationFrame(animationFrameId.current);
      animationFrameId.current = null;
    }
  }, [sequence.currentTimeMs]);

  const stop = useCallback(() => {
    setSequence(prev => ({ ...prev, isPlaying: false, scrubPosition: 0, currentTimeMs: 0 }));
    pausedTimeRef.current = 0;
    if (animationFrameId.current) {
      cancelAnimationFrame(animationFrameId.current);
      animationFrameId.current = null;
    }
  }, []);

  const setScrubPosition = useCallback((position: number) => {
    const clampedPosition = Math.max(0, Math.min(1, position));
    setSequence(prev => ({ 
      ...prev, 
      scrubPosition: clampedPosition,
      currentTimeMs: timeToScrubPosition({ ...prev, scrubPosition: clampedPosition }, clampedPosition)
    }));
  }, []);

  const setLoop = useCallback((loop: boolean) => {
    setSequence(prev => ({ ...prev, loop }));
  }, []);

  const addSlotAction = useCallback((pose: Pose, index?: number) => {
    setSequence(prev => {
      const next = addSlot(prev, pose, index);
      return autoInterpolationEnabled ? applyAutoInterpolation(next) : next;
    });
  }, [applyAutoInterpolation, autoInterpolationEnabled]);

  const removeSlotAction = useCallback((slotId: string) => {
    setSequence(prev => removeSlot(prev, slotId));
  }, []);

  const updateSlotAction = useCallback((slotId: string, pose: Pose) => {
    setSequence(prev => {
      const next = updateSlot(prev, slotId, pose);
      return autoInterpolationEnabled ? applyAutoInterpolation(next) : next;
    });
  }, [applyAutoInterpolation, autoInterpolationEnabled]);

  const reorderSlotsAction = useCallback((fromIndex: number, toIndex: number) => {
    setSequence(prev => reorderSlots(prev, fromIndex, toIndex));
  }, []);

  const updateSlotTransitionAction = useCallback((slotId: string, durationToNext: number, easing: EasingFunction) => {
    setSequence(prev => {
      const next = updateSlotTransition(prev, slotId, durationToNext, easing);
      return autoInterpolationEnabled ? applyAutoInterpolation(next) : next;
    });
  }, [applyAutoInterpolation, autoInterpolationEnabled]);

  const updateSlotLabelAction = useCallback((slotId: string, label: string) => {
    setSequence(prev => updateSlotLabel(prev, slotId, label));
  }, []);

  const setABMode = useCallback((poseA: Pose, poseB: Pose) => {
    setSequence(createABSequence(poseA, poseB));
  }, []);

  const setEasingEnabled = useCallback((enabled: boolean) => {
    setSequence(prev => ({ ...prev, easingEnabled: enabled }));
  }, []);

  const setSmoothTransitions = useCallback((enabled: boolean) => {
    setSequence(prev => ({ ...prev, smoothTransitions: enabled }));
  }, []);

  const setIKAssisted = useCallback((enabled: boolean) => {
    setSequence(prev => ({ ...prev, ikAssisted: enabled }));
  }, []);

  // Animation loop using requestAnimationFrame
  useEffect(() => {
    if (sequence.isPlaying && sequence.slots.length >= 2) {
      // Cancel any existing animation frame before starting new one
      if (animationFrameId.current) {
        cancelAnimationFrame(animationFrameId.current);
        animationFrameId.current = null;
      }
      
      // Update refs with current state
      depsRef.current = { 
        isPlaying: sequence.isPlaying, 
        slots: [...sequence.slots], // Create a stable copy
        loop: sequence.loop 
      };
      
      const animate = (timestamp: number) => {
        const { isPlaying, slots, loop } = depsRef.current;
        
        if (!isPlaying || slots.length < 2) {
          animationFrameId.current = null;
          return;
        }
        
        const elapsed = timestamp - startTimeRef.current;
        const totalDuration = slots.slice(0, -1).reduce((sum, slot) => sum + slot.durationToNext, 0);
        
        if (totalDuration === 0) {
          animationFrameId.current = null;
          return;
        }
        
        let currentTime = elapsed;
        
        if (loop) {
          currentTime = elapsed % totalDuration;
        } else if (elapsed >= totalDuration) {
          // Animation completed
          setSequence(prev => ({ 
            ...prev, 
            isPlaying: false, 
            currentTimeMs: totalDuration,
            scrubPosition: 1 
          }));
          animationFrameId.current = null;
          return;
        }
        
        setSequence(prev => ({ 
          ...prev, 
          currentTimeMs: currentTime,
          scrubPosition: timeToScrubPosition(prev, currentTime)
        }));
        
        animationFrameId.current = requestAnimationFrame(animate);
      };
      
      startTimeRef.current = performance.now() - pausedTimeRef.current;
      animationFrameId.current = requestAnimationFrame(animate);
    }
    
    return () => {
      if (animationFrameId.current) {
        cancelAnimationFrame(animationFrameId.current);
        animationFrameId.current = null;
      }
    };
  }, [sequence.isPlaying, sequence.loop]);

  const actions: SequenceActions = {
    setSequence,
    play,
    pause,
    stop,
    setScrubPosition,
    setLoop,
    addSlot: addSlotAction,
    removeSlot: removeSlotAction,
    updateSlot: updateSlotAction,
    reorderSlots: reorderSlotsAction,
    updateSlotTransition: updateSlotTransitionAction,
    updateSlotLabel: updateSlotLabelAction,
    setABMode,
    setEasingEnabled,
    setSmoothTransitions,
    setIKAssisted,
  };

  return [sequence, currentPose, actions];
};
